# Generated by Django 5.1.11 on 2025-08-09 07:15

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_stockquote_raw_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('indicators', models.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_indicators', to='market.company')),
            ],
            options={
                'unique_together': {('company', 'time')},
            },
        ),
    ]
